#spring:
#  application:
#    name: DBLab
#  datasource:
#    url: jdbc:h2:mem:vehicle;DB_CLOSE_ON_EXIT=FALSE;
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#        enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#      format-sql: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true
